name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.4'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          TF_VAR_my_variable: ${{ secrets.MY_SECRET }}
        run: terraform apply -auto-approve
